version: "3"
services:
  nginx:
    ports:
      - "80:80"

  programmer-server:
    build:
      context: .
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}